# Generated by Django 2.2.1 on 2019-05-31 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS unaccent;')
    ]
