# Generated by Django 2.2.1 on 2019-05-31 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True, verbose_name='Modified at')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True, verbose_name='Modified at')),
                ('name', models.CharField(db_column='tx_name', max_length=64, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True, verbose_name='Modified at')),
                ('content', models.TextField(db_column='tx_content', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'db_table': 'notice',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True, verbose_name='Modified at')),
                ('name', models.CharField(db_column='tx_name', max_length=64, unique=True, verbose_name='Name')),
                ('department', models.ForeignKey(db_column='id_department', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='core.Department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True, verbose_name='Modified at')),
                ('chat', models.ForeignKey(db_column='id_chat', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_users', to='core.Chat', verbose_name='Chat')),
                ('user', models.ForeignKey(db_column='id_user', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_users', to='core.User', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Chat user',
                'verbose_name_plural': 'Chat users',
                'db_table': 'chat_user',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True, verbose_name='Modified at')),
                ('message', models.TextField(db_column='tx_message', verbose_name='Message')),
                ('chat', models.ForeignKey(db_column='id_chat', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_messages', to='core.Chat', verbose_name='Chat')),
                ('user', models.ForeignKey(db_column='id_user', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_messages', to='core.User', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Chat message',
                'verbose_name_plural': 'Chat messages',
                'db_table': 'chat_message',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['department'], name='user_id_depa_4c2f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatuser',
            index=models.Index(fields=['user'], name='chat_user_id_user_02a982_idx'),
        ),
        migrations.AddIndex(
            model_name='chatuser',
            index=models.Index(fields=['chat'], name='chat_user_id_chat_043e6e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user'], name='chat_messag_id_user_e0cfbc_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat'], name='chat_messag_id_chat_2ed809_idx'),
        ),
    ]
